site_name: InteinFinder
site_url: https://mooreryan.github.io/intein_finder/
repo_url: https://github.com/mooreryan/intein_finder
edit_uri: edit/main/_docs_src/src
site_description: Installation and usage instructions for InteinFinder, a program for identifying inteins in large protein datasets.
site_author: Ryan M. Moore
nav:
  - InteinFinder: index.md
  - Overview:
    - Getting Started: getting-started.md
    - InteinFinder Use Cases: intein-finder-use-cases.md
    - Definitions & Jargon: jargon.md
    - Bibliography: bibliography.md
  - Installation:
    - Installing External Software Dependencies: installing-external-dependencies.md
    - Installing Precompiled Binaries: installing-precompiled-binaries.md
    - Installing With Docker: installing-with-docker.md
    - Installing From Source: installing-from-source.md
  - Usage:
    - Command Line Interface: cli.md
    - Output: intein-finder-output.md
  - Examples:
    - Tons of Examples: tons-of-examples.md
theme:
  name: readthedocs
  custom_dir: custom_theme
  highlightjs: true
  hljs_languages:
    - bash
    - toml
markdown_extensions:
  - meta
docs_dir: src
site_dir: ../_docs
