name: Build and Test Static

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  PROGRAM_NAME: intein_finder

jobs:
  build_and_test_static:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mooreryan/intein_finder_build_and_test_alpine:414a9c7

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - run: echo "LOCAL_PATH=$HOME/.local/bin" >> $GITHUB_ENV

      - name: Setup path
        run: |
          mkdir -p "$LOCAL_PATH"
          echo "$LOCAL_PATH" >> $GITHUB_PATH

      - name: Download MAFFT
        run: |
          \curl -L \
          https://mafft.cbrc.jp/alignment/software/mafft-7.490-without-extensions-src.tgz \
          | tar xz \
          && cd mafft-*/core/ && make clean && make && sudo make install

      - name: Download & Install MMseqs2
        run: |
          \curl -L \
          https://github.com/soedinglab/MMseqs2/releases/download/13-45111/mmseqs-linux-sse2.tar.gz \
          | tar xz \
          && mv mmseqs/bin/mmseqs "$LOCAL_PATH"

      - name: Download & Install NCBI BLAST+
        run: |
          \curl -L \
          https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.12.0/ncbi-blast-2.12.0+-x64-linux.tar.gz \
          | tar xz \
          && mv ncbi-blast-2.12.0+/bin/rpsblast "${LOCAL_PATH}/rpsblast+" \
          && mv ncbi-blast-2.12.0+/bin/makeprofiledb "${LOCAL_PATH}/makeprofiledb"

      - name: Install dune
        run: opam install dune

      - name: Install deps
        run: opam install --locked . --deps-only --with-doc --with-test

      - name: Build
        run: OCAMLPARAM=_,ccopt=-static opam exec -- make build_release

      - name: Test
        run: OCAMLPARAM=_,ccopt=-static opam exec -- make test_release

      - name: Upload the build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROGRAM_NAME }}-alpine-static
          path: _build/install/default/bin/${{ env.PROGRAM_NAME }}
